# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e514ac116bcf70bba90827349984bc7938cd20a419e18cad0e090a180eaa273ead2643c43d1cc0910dabf76a19c9ef6843924cdffe04eb63596f0af06890713

test:
  secret_key_base: 7edb453d2528291c1b26b2a437d0c286641f9013a594e14e4047034e3957dbad3bc58bd5f4e16b628e0de86834772dce31f1d9e0f3cd4f924b30df9080c85ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
